const GET_USER = "GET_USER";
const REGISTER_USER = "REGISTER_USER";
const UPDATE_USER = "UPDATE_USER";
const GET_ORDER = "GET_ORDER";
const REGISTER_ORDER = "REGISTER_ORDER";
const GET_ALL_ORDERS = "GET_ALL_ORDERS";
const GET_PRODUCT = "GET_PRODUCT";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const ADD_PRODUCT = "ADD_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const ADD_SHIPPING = "ADD_SHIPPING";
const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
const RESET_LOGIN_ERROR = "RESET_LOGIN_ERROR";
const RESET_REGISTER_ERROR = "RESET_REGISTER_ERROR";
const LOGIN = "LOGIN";
const SIGNUP = "SIGNUP";
const SIGN_OUT = "SIGN_OUT";
const SET_RESPONSE = "SET_RESPONSE";
const RESET_RESPONSE = "RESET_RESPONSE";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const UPDATE_QUANTITY = "UPDATE_QUANTITY";
const UPLOAD_IMAGE = "UPLOAD_IMAGE";
const RESET_ADD_PRODUCT_ERROR = "RESET_ADD_PRODUCT_ERROR";
const RESET_ADD_PRODUCT_SUCCESS = "RESET_ADD_PRODUCT_SUCCESS";
const GET_ALL_IMAGES = "GET_ALL_IMAGES";
const UPDATE_STATUS = "UPDATE_STATUS";
const UPDATE_STATUS_RESPONSE = "UPDATE_STATUS_RESPONSE";
const RESET_UPDATE_STATUS_RESPONSE = "RESET_UPDATE_STATUS_RESPONSE";
const ANONYM_USER = "ANONYM_USER";
const USER_CARD_INFO = "USER_CARD_INFO";
const SEARCH_PRODUCTS = "SEATCH_PRODUCTS";
export default {
  GET_ALL_ORDERS,
  GET_ALL_PRODUCTS,
  GET_ORDER,
  GET_PRODUCT,
  GET_USER,
  REGISTER_ORDER,
  REGISTER_USER,
  ADD_PRODUCT,
  UPDATE_PRODUCT,
  UPDATE_USER,
  ADD_SHIPPING,
  ADD_PAYMENT_METHOD,
  RESET_LOGIN_ERROR,
  RESET_REGISTER_ERROR,
  LOGIN,
  SIGNUP,
  SIGN_OUT,
  RESET_RESPONSE,
  SET_RESPONSE,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  UPDATE_QUANTITY,
  UPLOAD_IMAGE,
  DELETE_PRODUCT,
  RESET_ADD_PRODUCT_ERROR,
  RESET_ADD_PRODUCT_SUCCESS,
  GET_ALL_IMAGES,
  UPDATE_STATUS,
  UPDATE_STATUS_RESPONSE,
  RESET_UPDATE_STATUS_RESPONSE,
  ANONYM_USER,
  USER_CARD_INFO,
  SEARCH_PRODUCTS,
};
