const GET_USER = "GET_USER";
const REGISTER_USER = "REGISTER_USER";
const UPDATE_USER = "UPDATE_USER";
const GET_ORDER = "GET_ORDER";
const REGISTER_ORDER = "REGISTER_ORDER";
const GET_ALL_ORDERS = "GET_ALL_ORDERS";
const GET_PRODUCT = "GET_PRODUCT";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const ADD_PRODUCT = "ADD_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export default {
  GET_ALL_ORDERS,
  GET_ALL_PRODUCTS,
  GET_ORDER,
  GET_PRODUCT,
  GET_USER,
  REGISTER_ORDER,
  REGISTER_USER,
  ADD_PRODUCT,
  UPDATE_PRODUCT,
  UPDATE_USER,
};
