const SET_PRODUCTS = "SET_PRODUCTS";
const ADD_PRODUCT = "ADD_PRODUCT";
const ADD_SHIPPING = "ADD_SHIPPING";
const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
const RESET_LOGIN_ERROR = "RESET_LOGIN_ERROR";
const SET_USER = "SET_USER";
const SET_REGISTER_ERROR = "SET_REGISTER_ERROR";
const RESET_REGISTER_ERROR = "RESET_REGISTER_ERROR";
export default {
  SET_PRODUCTS,
  ADD_PRODUCT,
  ADD_PAYMENT_METHOD,
  ADD_SHIPPING,
  SET_LOGIN_ERROR,
  RESET_LOGIN_ERROR,
  SET_USER,
  SET_REGISTER_ERROR,
  RESET_REGISTER_ERROR,
};
