const SET_PRODUCTS = "SET_PRODUCTS";
const ADD_PRODUCT = "ADD_PRODUCT";
const ADD_SHIPPING = "ADD_SHIPPING";
const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
export default { SET_PRODUCTS, ADD_PRODUCT, ADD_PAYMENT_METHOD, ADD_SHIPPING };
